# Generated by Django 4.2.4 on 2023-12-06 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения')),
                ('name', models.CharField(help_text='Название представляет собой артикул товара, на который Вы хотите создать скидку', max_length=100, verbose_name='Название')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена со скидкой')),
                ('start_date', models.DateField(verbose_name='Дата начала акции')),
                ('end_date', models.DateField(verbose_name='Дата конца акции')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.discount', verbose_name='Скидка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Скидка на товар',
                'verbose_name_plural': 'Скидки на товары',
            },
        ),
    ]
