# Generated by Django 4.2.4 on 2024-01-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_country_of_origin_and_more'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdiscount',
            name='product',
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='products',
            field=models.ManyToManyField(to='store.product', verbose_name='Товары'),
        ),
    ]
