# Generated by Django 4.2.4 on 2023-09-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdiscount',
            options={'verbose_name': 'Скидка на товар', 'verbose_name_plural': 'Скидки на товары'},
        ),
    ]
