# Generated by Django 4.2.4 on 2023-10-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_alter_productdiscount_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='description',
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(help_text='Название представляет собой артикул товара, на который Вы хотите создать скидку', max_length=100, verbose_name='Название'),
        ),
    ]
