# Generated by Django 4.2.4 on 2023-12-06 16:27

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения')),
                ('color', models.CharField(max_length=20, unique=True, verbose_name='Цвет')),
                ('hex_number', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, validators=[django.core.validators.RegexValidator(regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Выберите цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('vendor_code', models.CharField(max_length=100, verbose_name='Артикул')),
                ('new_collection', models.BooleanField(default=True, verbose_name='Новая коллекция')),
                ('upper_material', models.CharField(choices=[('Genuine leather', 'Натуральная кожа')], default='Genuine leather', max_length=50, null=True, verbose_name='Материал верха')),
                ('lining_material', models.CharField(choices=[('Natural fur', 'Натуральный мех'), ('Baize', 'Байка')], max_length=50, null=True, verbose_name='Материал подкладки')),
                ('heel_height', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0, message='Высота каблука должна быть положительным значением')], verbose_name='Высота каблука')),
                ('sole_height', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0, message='Высота подошвы должна быть положительным значением')], verbose_name='Высота подошвы')),
                ('completeness', models.CharField(choices=[('Average', 'Средняя')], default='Average', max_length=50, null=True, verbose_name='Полнота')),
                ('true_to_size', models.CharField(choices=[('Exact size', 'Размер в размер')], default='Exact size', max_length=50, null=True, verbose_name='Соответствие размера')),
                ('country_of_origin', models.CharField(default='Турция', max_length=50, null=True, verbose_name='Страна производства')),
                ('guarantee_period', models.PositiveSmallIntegerField(null=True, verbose_name='Гарантийный срок (дней)')),
                ('importer', models.CharField(max_length=200, null=True, verbose_name='Импортер')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('quantity', models.PositiveSmallIntegerField(default=2, verbose_name='Количество')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.color', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='SeasonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения')),
                ('size', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(35, message='Допустимый размер: 35-41.'), django.core.validators.MaxValueValidator(41, message='Допустимый размер: 35-41.')], verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='TypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярная категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения')),
                ('vendor_code', models.CharField(default='-', max_length=100, verbose_name='Артикул')),
                ('products', models.ManyToManyField(blank=True, null=True, to='store.product', verbose_name='Товары')),
                ('sizes', models.ManyToManyField(to='store.size', verbose_name='Размеры в наличии')),
            ],
            options={
                'verbose_name': 'Размер товара',
                'verbose_name_plural': 'Размеры товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения')),
                ('image', models.FileField(upload_to='product_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))], verbose_name='Изображение')),
                ('primary', models.BooleanField(default=False, verbose_name='Основная фотография')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='season_category',
            field=models.ManyToManyField(to='store.seasoncategory', verbose_name='Сезон'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.size', verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.typecategory', verbose_name='Категория'),
        ),
    ]
