# Generated by Django 4.2.4 on 2024-01-15 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, default='Турция', max_length=50, null=True, verbose_name='Страна производства'),
        ),
        migrations.AlterField(
            model_name='product',
            name='guarantee_period',
            field=models.PositiveSmallIntegerField(default=30, null=True, verbose_name='Гарантийный срок (дней)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='heel_height',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Высота каблука должна быть положительным значением')], verbose_name='Высота каблука (см)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='importer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Импортер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lining_material',
            field=models.CharField(choices=[('Natural fur', 'Натуральный мех'), ('Baize', 'Байка'), ('Genuine leather', 'Натуральная кожа')], default='Genuine leather', max_length=50, null=True, verbose_name='Материал подкладки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sole_height',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Высота подошвы должна быть положительным значением')], verbose_name='Высота подошвы (см)'),
        ),
    ]
