# Generated by Django 4.2.4 on 2024-07-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_country_of_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='completeness',
        ),
        migrations.RemoveField(
            model_name='product',
            name='heel_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sole_height',
        ),
    ]
