# Generated by Django 4.2.4 on 2023-09-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productimage_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_collection',
            field=models.BooleanField(default=False),
        ),
    ]
