# Generated by Django 4.2.4 on 2023-09-17 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_new_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AddField(
            model_name='product',
            name='completeness',
            field=models.CharField(choices=[('Average', 'Средняя')], max_length=50, null=True, verbose_name='Полнота'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(max_length=50, null=True, verbose_name='Страна производства'),
        ),
        migrations.AddField(
            model_name='product',
            name='guarantee_period',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Гарантийный срок'),
        ),
        migrations.AddField(
            model_name='product',
            name='heel_height',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0, message='Высота каблука должна быть положительным значением')]),
        ),
        migrations.AddField(
            model_name='product',
            name='importer',
            field=models.CharField(max_length=200, null=True, verbose_name='Импортер'),
        ),
        migrations.AddField(
            model_name='product',
            name='lining_material',
            field=models.CharField(choices=[('Natural fur', 'Натуральный мех'), ('Baize', 'Байка')], max_length=50, null=True, verbose_name='Материал подкладки'),
        ),
        migrations.AddField(
            model_name='product',
            name='sole_height',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0, message='Высота подошвы должна быть положительным значением')]),
        ),
        migrations.AddField(
            model_name='product',
            name='true_to_size',
            field=models.CharField(choices=[('Exact size', 'Размер в размер')], max_length=50, null=True, verbose_name='Соответствие размера'),
        ),
        migrations.AddField(
            model_name='product',
            name='upper_material',
            field=models.CharField(choices=[('Genuine leather', 'Натуральная кожа')], max_length=50, null=True, verbose_name='Материал верха'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='season_category',
        ),
        migrations.AddField(
            model_name='product',
            name='season_category',
            field=models.ManyToManyField(to='store.seasoncategory', verbose_name='Сезон'),
        ),
    ]
