# Generated by Django 4.2.4 on 2024-08-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_completeness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='vendor_code',
            field=models.CharField(default='-', max_length=100, unique=True, verbose_name='Артикул'),
        ),
    ]
