# Generated by Django 4.2.4 on 2023-10-06 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productimage_options_product_completeness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='heel_height',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0, message='Высота каблука должна быть положительным значением')], verbose_name='Высота каблука'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_collection',
            field=models.BooleanField(default=False, verbose_name='Новая коллекция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sole_height',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0, message='Высота подошвы должна быть положительным значением')], verbose_name='Высота подошвы'),
        ),
    ]
