# Generated by Django 4.2.4 on 2023-10-27 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_color_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='vendor_code',
            field=models.CharField(default='-', max_length=100, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='completeness',
            field=models.CharField(choices=[('Average', 'Средняя')], default='Average', max_length=50, null=True, verbose_name='Полнота'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(default='Турция', max_length=50, null=True, verbose_name='Страна производства'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_collection',
            field=models.BooleanField(default=True, verbose_name='Новая коллекция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='true_to_size',
            field=models.CharField(choices=[('Exact size', 'Размер в размер')], default='Exact size', max_length=50, null=True, verbose_name='Соответствие размера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='upper_material',
            field=models.CharField(choices=[('Genuine leather', 'Натуральная кожа')], default='Genuine leather', max_length=50, null=True, verbose_name='Материал верха'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(35, message='Допустимый размер: 35-41.'), django.core.validators.MaxValueValidator(41, message='Допустимый размер: 35-41.')], verbose_name='Размер'),
        ),
    ]
