# Generated by Django 4.2.4 on 2023-10-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_productsize_product_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='store.product', verbose_name='Товары'),
        ),
    ]
