# Generated by Django 4.2.4 on 2023-10-30 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productsize_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasoncategory',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(35, message='Допустимый размер: 35-41.'), django.core.validators.MaxValueValidator(41, message='Допустимый размер: 35-41.')], verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='typecategory',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
