# Generated by Django 4.2.4 on 2023-11-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_seasoncategory_name_alter_size_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='guarantee_period',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Гарантийный срок (дней)'),
        ),
    ]
