# Generated by Django 4.2.4 on 2023-11-16 13:16

import colorfield.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_guarantee_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_number',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, validators=[django.core.validators.RegexValidator(regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Выберите цвет'),
        ),
    ]
