# Generated by Django 4.2.4 on 2024-01-20 00:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_alter_product_country_of_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))], verbose_name='Изображение')),
                ('main', models.BooleanField(default=False, verbose_name='Главная фотография')),
                ('season_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.seasoncategory', verbose_name='Фотография сезона')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
