# Generated by Django 4.2.4 on 2024-01-16 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))], verbose_name='Изображение')),
                ('main', models.BooleanField(default=False, verbose_name='Главная фотография')),
                ('popular_categories', models.BooleanField(default=False, verbose_name='Фотография популярных категорий')),
            ],
        ),
    ]
