# Generated by Django 4.2.4 on 2023-09-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'В ожидании обработки'), ('Processing', 'Обрабатывается'), ('Shipped', 'Передан курьеру'), ('Delivered', 'Доставлен'), ('Canceled', 'Отменен')], default='Pending', max_length=50, verbose_name="Статус"),
        ),
    ]
