# Generated by Django 4.2.4 on 2024-01-15 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Введите действительный адрес электронной почты.')], verbose_name='Электронный адрес'),
        ),
    ]
