# Generated by Django 4.2.4 on 2023-11-04 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения')),
                ('latest_posts', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
